lib/garage_client/client.rb
spec/garage_client/client_spec.rb

Client endpoint option check -> [here](https://github.com/cookpad/garage_client/blob/master/lib/garage_client/client.rb#L84)
but `default_options#endpoint` rise error when not set default endpoint. -> [here](https://github.com/cookpad/garage_client/blob/master/lib/garage_client/configuration.rb#L41)

:bug: Fix client endpoint option bug

---

garage_client.gemspec

garage_client doesn't use mime-types.

Remove needless dependency to mime-types

---

lib/garage_client/resource.rb
lib/garage_client/response.rb
spec/garage_client/response_spec.rb

Without respond_to_missing? overridden, `method` method would fail with
NameError.
@cookpad/garage please review

Override respond_to_missing? when method_missing is overridden

---

lib/garage_client/resource.rb
lib/garage_client/response.rb

Before:
```
lib/garage_client/response.rb:111:in `method_missing': undefined method `name' for #<GarageClient::Response:0x00000002fdebf0> (NoMethodError)
```
After:
```
lib/garage_client/resource.rb:51:in `method_missing': undefined method `name' for #<Hashie::Mash error="Sorry, something went wrong"> (NoMethodError)
```
@cookpad/garage What do you think?

Better error message for unexpected property access

---

lib/garage_client/error.rb
lib/garage_client/response/raise_http_exception.rb
spec/garage_client/response_spec.rb

Error raised, when a API returns 4xx client errors or 5xx server errors.
@cookpad/dev-infra :eyeglasses:

Add 4xx client errors and 5xx server errors handling

---

.travis.yml
Guardfile
garage_client.gemspec
spec/garage_client/request/json_encoded_spec.rb

Since guard.gem depends on listen and latest listen can't be installed with Ruby < 2.2.3, travis CI is failing.
I dropped unused guard.gem and changed Ruby versions to run on CI.

Fix failing CI

---

lib/garage_client/error.rb

Since all exception's base class is GarageClient::Error, we can't rescue all 4xx errors or 5xx errors.
I changed 4xx erros to be a subclass of `ClientError` and 5xx errors to be a subclass of `ServerError`.

Allow rescuing 4xx or 5xx errors

---

README.md
lib/garage_client/client.rb
lib/garage_client/configuration.rb
spec/features/configuration_spec.rb
spec/garage_client/client_spec.rb
spec/garage_client/configuration_spec.rb
spec/spec_helper.rb

For easy understanding from access logs what application is accessing.
@cookpad/garage @cookpad/dev-infra What do you think?

Require application name for embedding as User-Agent

---

README.md
garage_client.gemspec
lib/garage_client.rb
lib/garage_client/railtie.rb
spec/garage_client/railtie_spec.rb

Related to: https://github.com/cookpad/garage_client/pull/14
This patch introduces a railtie which sets Rails application name to `GarageClient.configuration.name` if it's not specified. When `Rails.application.class` is `Cookpad::Application`, `GarageClient.configuration.name` will be `"cookpad"`.
@cookpad/dev-infra How do you think about this?

Set rails application name by default

---

.travis.yml

rack 2 requires ruby version >= 2.2.2
garage_client depends on rack through rails only in development dependencies,
so there is no necessity to set gem.required_ruby_version.
WDYT?

Do not support under 2.2.2

---

lib/garage_client/railtie.rb

[garage_client-rails](https://github.com/tokubai/garage_client-rails)
has `GarageClient::Rails` module, so this initializer method misses
`Rails.application` method.

See top level Rails

---

README.md
lib/garage_client/client.rb

@cookpad/dev-infra @KOBA789 please have a look

Enforce global name explicitly

---

lib/garage_client/cachers/base.rb

Current master branch can't pass tests due to Faraday's changes.
https://travis-ci.org/cookpad/garage_client/builds/210856611
Faraday::Env inherites Faraday::Options and its #merge! is different
from Hash#merge!. The method does not use given block and failed
merging when a value in `@env` with a key (A) is not nil but another
value in `response.env` with same key (A) is nil with NomethodError
on nil. The cause of the degression might be brought by
https://github.com/lostisland/faraday/pull/662 but I'm not sure now.
So for now, just work-around by using more primitive method, #each,
instread.
@cookpad/dev-infra FYI

Support latest faraday

---

README.md
garage_client.gemspec
lib/garage_client.rb
lib/garage_client/client.rb
spec/features/tracing_spec.rb

Suport ditributed tracing by adding configuration and set the configured tracer to Faraday middleware stack.
At first, we use [aws-xray](https://github.com/taiki45/aws-xray) tracer. But tracers are configurable and users should be able to choose or implement another tracing method.
@cookpad/dev-infra Please take a look at this.

Distributed tracing support

---

lib/garage_client/client.rb
spec/features/tracing_spec.rb

Re-order trace middleware to record HTTP request/response when HTTP errors are occured. Since garage_client raises an error on 4xx and 5xx, we have to place tracing middleware after RaiseHttpException middleware.
@cookpad/dev-infra FYI

Record http request/response even if API returns errors.

---

README.md
lib/garage_client/client.rb

By https://github.com/taiki45/aws-xray/pull/77, we don't require faraday middleware by default.
@cookpad/dev-infra FYI

Require aws-xray's faraday middleware

---

lib/garage_client/resource.rb
spec/garage_client/resource_spec.rb

It would be nice if `GarageClient::Resource` provided a fluent interface similar to how [ActiveRecord allows querying of attributes](https://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Query.html#method-i-query_attribute). The data in a `GarageClient::Resource` is in a [`Hashie::Mash`](https://github.com/intridea/hashie#methodaccess), which already provides querying of attributes.
This proposed change passes "query" style methods to the underlying Hashie::Mash.
e.g.
```ruby
resource.title
resource.title?
resource.product_id
resource.product_id?
```

Support query methods on GarageClient::Resource

---

.travis.yml
garage_client.gemspec

This pull request refactors about Ruby version. It does not affect user.
This pull request will update two things.
.travis.yml
---
First, it updates .travis.yml. I added new minor versions (2.5.3 and 2.4.5), and updated teeny versions (2.3.8 and 2.2.10).
88e80c1
Remove an unused dependency
---
Secondly, it removes an unused dependency, which is `system_timer`.
It is available with Ruby 1.8 or older, but garage_client does not support Ruby 1.8. This dependency is no longer needed.
1b815e8

Refactoring about Ruby versions

---

lib/garage_client/railtie.rb

This PR suppresses DEPRECATION WARNING related to [this changes on Rails6](https://github.com/rails/rails/pull/34051).
I checked it works fine for my application based on Rails5.2 and Rails6 rc1 by this PR.
Please take a look.

Use Module#module_parent_name for Rails6

---

garage_client.gemspec
lib/garage_client.rb
spec/garage_client/cacher_spec.rb
spec/spec_helper.rb

Remove atcivesupport from runtime dependency. It's only used sparingly in the spec.

Remove dependency on activesupport

---

spec/garage_client/cacher_spec.rb

The failure message suggests that we should remove the surrounding block altogether if tests are running with faraday > 1.0.0, but I don't really understand why the version of faraday with which tests are running matters when we still support 0.8.0 <= faraday < 1.0.0, so I just removed the failing test for now (though to be honest I'm not really sure what those tests which were added in #2 are trying to ensure).
https://github.com/cookpad/garage_client/blob/6562ae8b816a913029d26189d630050e21ef32d8/garage_client.gemspec#L19
CI is currently failing because of this test: https://travis-ci.org/github/cookpad/garage_client/jobs/750566301

Remove test that fails if faraday version is 1.0.0 or later

---

lib/garage_client/request/propagate_request_id.rb
spec/garage_client/request/propagate_request_id_spec.rb

I think a key for `env[:request_headers]` is expected to just be an HTTP header name instead of HTTP_HEADER_NAME.
https://github.com/lostisland/faraday/blob/v0.8.0/lib/faraday/adapter/net_http.rb#L57
https://github.com/lostisland/faraday/blob/v0.8.0/lib/faraday/adapter/typhoeus.rb#L37

Fix request ID not being propagated

---

.travis.yml

I'd like to drop support for Ruby 2.4 and older as they have reached their EOL: https://www.ruby-lang.org/en/downloads/branches/

Drop support for Ruby < 2.5

---

lib/garage_client.rb

#29 has removed the runtime dependency on the activesupport gem and removed `require 'active_support/all'` but the [`Module.delegate`](https://api.rubyonrails.org/classes/Module.html#method-i-delegate) method added by Active Support core extensions is still used, thus causing a NoMethodError error if the extension is not loaded.
```
$ cat Gemfile
source 'https://rubygems.org'
gem 'garage_client'
$ bundle info garage_client
* garage_client (2.4.4)
...
$ bundle exec irb -r garage_client
...
/path/to/garage_client/lib/garage_client.rb:27:in `block in singleton class': undefined method `delegate' for #<Class:GarageClient> (NoMethodError)
Did you mean?  DelegateClass
```

Stop using Module.delegate method

---

lib/garage_client/client.rb

#29 has removed the runtime dependency on the activesupport gem and removed `require 'active_support/all'` but the [`Hash#stringify_keys`](https://api.rubyonrails.org/classes/Hash.html#method-i-stringify_keys) method added by Active Support core extensions is still used, thus causing a NoMethodError error if the extension is not loaded.
```
$ cat Gemfile
source 'https://rubygems.org'
gem 'garage_client', git: 'https://github.com/cookpad/garage_client'
$ bundle info garage_client
* garage_client (2.4.4 1bdc412)
...
$ bundle exec irb -r garage_client
irb(main):001:0> GarageClient.headers = {}
=> {}
irb(main):002:0> GarageClient::Client.new(endpoint: 'foo').headers
...
1: from /path/to/garage_client/lib/garage_client/client.rb:30:in `headers'
NoMethodError (undefined method `stringify_keys' …
```

Stop using Hash#stringify_keys method

---

lib/garage_client/client.rb

Since https://github.com/lostisland/faraday/releases/tag/v1.7.1 , `Faraday::Connection#authorization` is marked as deprecated.
See also: https://github.com/lostisland/faraday/pull/1306
When running the tests which use Faraday 1.10.1, I found that the following deprecation warning is shown in log.
> WARNING: `Faraday::Connection#authorization` is deprecated; it will be removed in version 2.0.
While initializing your connection, use `#request(:authorization, ...)` instead.
See https://lostisland.github.io/faraday/middleware/authentication for more usage info.
This PR aims to avoid using `Faraday::Connection#authorization` to fix the deprecation warning.

Fix deprecation warning caused by using Faraday::Connection#authorization
